# Generated by Django 2.1.5 on 2019-04-26 08:11

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='articletype',
            options={'verbose_name': '首页导航种类', 'verbose_name_plural': '首页导航种类'},
        ),
        migrations.RenameField(
            model_name='articletype',
            old_name='name',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleType', verbose_name='文章分类'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='文章详情'),
        ),
    ]
