# Generated by Django 2.1.5 on 2019-04-29 16:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllRequestCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='网站访问总次数')),
            ],
            options={
                'verbose_name': '网站访问总次数',
                'verbose_name_plural': '网站访问总次数',
            },
        ),
        migrations.CreateModel(
            name='DayRequestCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='日期')),
                ('count', models.IntegerField(default=1, verbose_name='单日访问次数')),
            ],
            options={
                'verbose_name': '网站日访问量',
                'verbose_name_plural': '网站日访问量',
            },
        ),
        migrations.CreateModel(
            name='RequestDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='访问时间')),
            ],
            options={
                'verbose_name': '访问记录详情',
                'verbose_name_plural': '访问记录详情',
            },
        ),
        migrations.CreateModel(
            name='UserIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='IP地址')),
                ('count', models.IntegerField(default=1, verbose_name='访问次数')),
            ],
            options={
                'verbose_name': '访问用户信息',
                'verbose_name_plural': '访问用户信息',
            },
        ),
        migrations.AddField(
            model_name='requestdate',
            name='user_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercount.UserIp', verbose_name='IP地址'),
        ),
    ]
